### ISSUE TITLE
终于在这儿找到了数据集！谢谢🙏🙏！

### ISSUE THREAD

**Issue by moneyDboat** [nju161250102/AI_challenger#1]

**Comment by ljzsky** [comment]
> _No description provided._

这个库的This repository is over its data quota.，哭了:'（，能发我一份数据集吗？感谢！

**Comment by ljzsky** [comment]
> > _No description provided._
> 
> 这个库的This repository is over its data quota.，哭了:'（，能发我一份数据集吗？感谢！

945680757@qq.com

**Comment by Vimos** [comment]
等候一个搬运
